//------------------------------------------------------------------------------
//LuaVarConstants                                                           UNIT
//------------------------------------------------------------------------------
//	What it does-
//		Used in lua script for getvar function.
//
//	Changes -
//		[2007/12/30] Aeomin - Created.
//
//------------------------------------------------------------------------------
unit LuaVarConstants;

{$IFDEF FPC}
{$MODE Delphi}
{$ENDIF}

interface

const

// 0 is reserved for default string based getvar.
VAR_SPEED = 1;
VAR_EXP = 2;
VAR_JOBEXP = 3;
VAR_VIRTUE = 4;
VAR_HONOR = 5;
VAR_HP = 6;
VAR_MAXHP = 7;
VAR_SP = 8;
VAR_MAXSP = 9;
VAR_POINT = 10;
VAR_HAIRCOLOR = 11;
VAR_CLEVEL = 12;
VAR_SPPOINT = 13;
VAR_STR = 14;
VAR_AGI = 15;
VAR_VIT = 16;
VAR_INT = 17;
VAR_DEX = 18;
VAR_LUK = 19;
VAR_JOB = 20;
VAR_MONEY = 21;
VAR_SEX = 22;
VAR_MAXEXP = 23;
VAR_MAXJOBEXP = 24;
VAR_WEIGHT = 25;
VAR_MAXWEIGHT = 26;
VAR_POISON = 27;
VAR_STONE = 28;
VAR_CURSE = 29;
VAR_FREEZING = 30;
VAR_SILENCE = 31;
VAR_CONFUSION = 32;
VAR_STANDARD_STR = 33;
VAR_STANDARD_AGI = 34;
VAR_STANDARD_VIT = 35;
VAR_STANDARD_INT = 36;
VAR_STANDARD_DEX = 37;
VAR_STANDARD_LUK = 38;
VAR_ATTACKMT = 39;
VAR_ATTACKEDMT = 40;
VAR_NV_BASIC = 41;
VAR_ATTPOWER = 42;
VAR_REFININGPOWER = 43;
VAR_MAX_MATTPOWER = 44;
VAR_MIN_MATTPOWER = 45;
VAR_ITEMDEFPOWER = 46;
VAR_PLUSDEFPOWER = 47;
VAR_MDEFPOWER = 48;
VAR_PLUSMDEFPOWER = 49;
VAR_HITSUCCESSVALUE = 50;
VAR_AVOIDSUCCESSVALUE = 51;
VAR_PLUSAVOIDSUCCESSVALUE = 52;
VAR_CRITICALSUCCESSVALUE = 53;
VAR_ASPD = 54;
VAR_PLUSASPD = 55;
VAR_JOBLEVEL = 56;
VAR_ACCESSORY2 = 57;
VAR_ACCESSORY3 = 58;
VAR_HEADPALETTE = 59;
VAR_BODYPALETTE = 60;
VAR_SHIELD = 61;
VAR_CURXPOS = 62;
VAR_CURYPOS = 63;
VAR_CURDIR = 64;
VAR_CHARACTERID = 65;
VAR_ACCOUNTID = 66;
VAR_MAPID = 67;
VAR_MAPNAME = 68;
VAR_ACCOUNTNAME = 69;
VAR_CHARACTERNAME = 70;
VAR_ITEM_COUNT = 71;
VAR_ITEM_ITID = 72;
VAR_ITEM_SLOT1 = 73;
VAR_ITEM_SLOT2 = 74;
VAR_ITEM_SLOT3 = 75;
VAR_ITEM_SLOT4 = 76;
VAR_HEAD = 77;
VAR_WEAPON = 78;
VAR_ACCESSORY = 79;
VAR_STATE = 80;
VAR_MOVEREQTIME = 81;
VAR_GROUPID = 82;
VAR_ATTPOWERPLUSTIME = 83;
VAR_ATTPOWERPLUSPERCENT = 84;
VAR_DEFPOWERPLUSTIME = 85;
VAR_DEFPOWERPLUSPERCENT = 86;
VAR_DAMAGENOMOTIONTIME = 87;
VAR_BODYSTATE = 88;
VAR_HEALTHSTATE = 89;
VAR_RESETHEALTHSTATE = 90;
VAR_CURRENTSTATE = 91;
VAR_RESETEFFECTIVE = 92;
VAR_GETEFFECTIVE = 93;
VAR_EFFECTSTATE = 94;
VAR_SIGHTABILITYEXPIREDTIME = 95;
VAR_SIGHTRANGE = 96;
VAR_SIGHTPLUSATTPOWER = 97;
VAR_STREFFECTIVETIME = 98;
VAR_AGIEFFECTIVETIME = 99;
VAR_VITEFFECTIVETIME = 100;
VAR_INTEFFECTIVETIME = 101;
VAR_DEXEFFECTIVETIME = 102;
VAR_LUKEFFECTIVETIME = 103;
VAR_STRAMOUNT = 104;
VAR_AGIAMOUNT = 105;
VAR_VITAMOUNT = 106;
VAR_INTAMOUNT = 107;
VAR_DEXAMOUNT = 108;
VAR_LUKAMOUNT = 109;
VAR_MAXHPAMOUNT = 110;
VAR_MAXSPAMOUNT = 111;
VAR_MAXHPPERCENT = 112;
VAR_MAXSPPERCENT = 113;
VAR_HPACCELERATION = 114;
VAR_SPACCELERATION = 115;
VAR_SPEEDAMOUNT = 116;
VAR_SPEEDDELTA = 117;
VAR_SPEEDDELTA2 = 118;
VAR_PLUSATTRANGE = 119;
VAR_DISCOUNTPERCENT = 120;
VAR_AVOIDABLESUCCESSPERCENT = 121;
VAR_STATUSDEFPOWER = 122;
VAR_PLUSDEFPOWERINACOLYTE = 123;
VAR_MAGICITEMDEFPOWER = 124;
VAR_MAGICSTATUSDEFPOWER = 125;
VAR_CLASS = 126;
VAR_PLUSATTACKPOWEROFITEM = 127;
VAR_PLUSDEFPOWEROFITEM = 128;
VAR_PLUSMDEFPOWEROFITEM = 129;
VAR_PLUSARROWPOWEROFITEM = 130;
VAR_PLUSATTREFININGPOWEROFITEM = 131;
VAR_PLUSDEFREFININGPOWEROFITEM = 132;
VAR_IDENTIFYNUMBER = 133;
VAR_ISDAMAGED = 134;
VAR_ISIDENTIFIED = 135;
VAR_REFININGLEVEL = 136;
VAR_WEARSTATE = 137;
VAR_ISLUCKY = 138;
VAR_ATTACKPROPERTY = 139;
VAR_STORMGUSTCNT = 140;
VAR_MAGICATKPERCENT = 141;
VAR_MYMOBCOUNT = 142;
VAR_ISCARTON = 143;
VAR_GDID = 144;
VAR_NPCXSIZE = 145;
VAR_NPCYSIZE = 146;
VAR_RACE = 147;
VAR_SCALE = 148;
VAR_PROPERTY = 149;
VAR_PLUSATTACKPOWEROFITEM_RHAND = 150;
VAR_PLUSATTACKPOWEROFITEM_LHAND = 151;
VAR_PLUSATTREFININGPOWEROFITEM_RHAND = 152;
VAR_PLUSATTREFININGPOWEROFITEM_LHAND = 153;
VAR_TOLERACE = 154;
VAR_ARMORPROPERTY = 155;
VAR_ISMAGICIMMUNE = 156;
VAR_ISFALCON = 157;
VAR_ISRIDING = 158;
VAR_MODIFIED = 159;
VAR_FULLNESS = 160;
VAR_RELATIONSHIP = 161;
VAR_ACCESSARY = 162;
VAR_SIZETYPE = 163;
VAR_SHOES = 164;
VAR_STATUSATTACKPOWER = 165;
VAR_BASICAVOIDANCE = 166;
VAR_BASICHIT = 167;
VAR_PLUSASPDPERCENT = 168;
VAR_CPARTY = 169;
VAR_ISMARRIED = 170;
VAR_ISGUILD = 171;
VAR_ISFALCONON = 172;
VAR_ISPECOON = 173;
VAR_ISPARTYMASTER = 174;
VAR_ISGUILDMASTER = 175;
VAR_BODYSTATENORMAL = 176;
VAR_HEALTHSTATENORMAL = 177;
VAR_STUN = 178;
VAR_SLEEP = 179;
VAR_UNDEAD = 180;
VAR_BLIND = 181;
VAR_BLOODING = 182;
VAR_BSPOINT = 183;
VAR_ACPOINT = 184;
VAR_BSRANK = 185;
VAR_ACRANK = 186;
VAR_CHANGESPEED = 187;
VAR_CHANGESPEEDTIME = 188;
VAR_MAGICATKPOWER = 189;

implementation

end.